/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package drive.mate.instructor;


import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import java.sql.SQLException;


/**
 *
 * @author smbha
 */
public class AddNewUserScreen extends javax.swing.JFrame {

    /**
     * Creates new form AddNewUser
     */
    public AddNewUserScreen() {
        initComponents();

        Image icon = new ImageIcon(this.getClass().getResource("/res/logo.png")).getImage();
        this.setIconImage(icon);

        ImageIcon logoIcon = new ImageIcon(this.getClass().getResource("/res/logo.png"));

        Image scaledImage = logoIcon.getImage().getScaledInstance(logolbl.getWidth(), logolbl.getHeight(), Image.SCALE_SMOOTH);
        logoIcon = new ImageIcon(scaledImage);

        // Set the scaled image to the JLabel
        logolbl.setIcon(logoIcon);

        this.setExtendedState(this.MAXIMIZED_BOTH);
        setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE); // Prevent default close operation

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                AlertMessages.conformExit(); // Call the method from AlertMessages class
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adduserpanel = new javax.swing.JPanel();
        createAccountbtn = new javax.swing.JButton();
        nicGet = new javax.swing.JTextField();
        usernameGet = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        logolbl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        backOption = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adduserpanel.setBackground(new java.awt.Color(31, 31, 31));

        createAccountbtn.setBackground(new java.awt.Color(252, 236, 32));
        createAccountbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createAccountbtn.setForeground(new java.awt.Color(51, 51, 51));
        createAccountbtn.setText("CREATE ACCOUNT");
        createAccountbtn.setBorder(null);
        createAccountbtn.setPreferredSize(new java.awt.Dimension(300, 45));
        createAccountbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountbtnActionPerformed(evt);
            }
        });

        nicGet.setBackground(new java.awt.Color(31, 31, 31));
        nicGet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nicGet.setForeground(new java.awt.Color(255, 255, 255));
        nicGet.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nicGet.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "NIC NO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        nicGet.setPreferredSize(new java.awt.Dimension(300, 55));
        nicGet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nicGetKeyPressed(evt);
            }
        });

        usernameGet.setBackground(new java.awt.Color(31, 31, 31));
        usernameGet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameGet.setForeground(new java.awt.Color(255, 255, 255));
        usernameGet.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameGet.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "NAME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        usernameGet.setPreferredSize(new java.awt.Dimension(300, 55));
        usernameGet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameGetKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 236, 32));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD NEW USER");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        logolbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logolbl.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout adduserpanelLayout = new javax.swing.GroupLayout(adduserpanel);
        adduserpanel.setLayout(adduserpanelLayout);
        adduserpanelLayout.setHorizontalGroup(
            adduserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adduserpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logolbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(adduserpanelLayout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addGroup(adduserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createAccountbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(adduserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(adduserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nicGet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameGet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1)))
                .addGap(0, 210, Short.MAX_VALUE))
        );

        adduserpanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {createAccountbtn, jLabel1, nicGet, usernameGet});

        adduserpanelLayout.setVerticalGroup(
            adduserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adduserpanelLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(logolbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(usernameGet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(nicGet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(createAccountbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        backOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/back.png"))); // NOI18N
        backOption.setText("Back");
        backOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backOptionMouseClicked(evt);
            }
        });
        backOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backOptionActionPerformed(evt);
            }
        });
        jMenuBar1.add(backOption);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adduserpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(adduserpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createAccountbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountbtnActionPerformed
        String username = usernameGet.getText();
        String nicno = nicGet.getText();

        // Check if the text boxes are empty
        if (username.isEmpty() || nicno.isEmpty()) {
            AlertMessages.showNullMessage("Please fill in all fields.");
        } else {
            try {
                // Check if user already exists
                if (AddNewUser.userExists(username, nicno)) {
                    AlertMessages.showFailedMessage("User already exists!");
                } else {
                    // Call the addUser function
                    boolean userAdded = AddNewUser.addUser(username, nicno);
                    if (userAdded) {
                        AlertMessages.showSuccessMessage("User added successfully.");
                        usernameGet.setText("");
                        nicGet.setText("");
                    } else {
                        AlertMessages.showFailedMessage("An error occurred. Try again!");
                    }
                }
            } catch (SQLException e) {
                e.printStackTrace(); 
                AlertMessages.showFailedMessage("An error occurred. Try again!");
            }
        }


    }//GEN-LAST:event_createAccountbtnActionPerformed

    private void backOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backOptionActionPerformed

    }//GEN-LAST:event_backOptionActionPerformed

    private void backOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backOptionMouseClicked
        new HomeInstructerScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backOptionMouseClicked

    private void usernameGetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameGetKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            nicGet.requestFocusInWindow();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            nicGet.requestFocusInWindow();
        }
    }//GEN-LAST:event_usernameGetKeyPressed

    private void nicGetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicGetKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            createAccountbtn.doClick();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            usernameGet.requestFocusInWindow();
        }
    }//GEN-LAST:event_nicGetKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewUserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewUserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewUserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewUserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewUserScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adduserpanel;
    private javax.swing.JMenu backOption;
    private javax.swing.JButton createAccountbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel logolbl;
    private javax.swing.JTextField nicGet;
    private javax.swing.JTextField usernameGet;
    // End of variables declaration//GEN-END:variables
}
